###ALL TECHNICIANSKILL
GET http://localhost:3000/Api/AllTS

###ALL CLIENT
GET http://localhost:3000/Api/AllClients

###ALL CALLCENTRE
GET http://localhost:3000/Api/AllCalls

###ALL CLIENTUSER
GET http://localhost:3000/Api/AllUsers

###ALL CONTRACT
GET http://localhost:3000/Api/AllContracts

###ALL EMPLOYEE
GET http://localhost:3000/Api/AllEmployees

###ALL JOB
GET http://localhost:3000/Api/AllJobs

###ALL JOBDESCRIPTION
GET http://localhost:3000/Api/AllJobDescriptions

###ALL PROBLEM
GET http://localhost:3000/Api/AllProblems

###ALL PROBLEMCALL
GET http://localhost:3000/Api/AllProblemCalls

###ALL CLIENTCONTRACT
GET http://localhost:3000/Api/AllClientContracts

###ALL SERVICECONTRACT
GET http://localhost:3000/Api/AllServiceContracts

###ALL SERVICE
GET http://localhost:3000/Api/AllServices